import type { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateP0Schema1778769900000 implements MigrationInterface {
  name = 'CreateP0Schema1778769900000';

  async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of createTableSql) {
      await queryRunner.query(sql);
    }
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    for (const tableName of dropOrder) {
      await queryRunner.query(`DROP TABLE IF EXISTS \`${tableName}\``);
    }
  }
}

const createTableSql = [
  `CREATE TABLE IF NOT EXISTS \`sdd_users\` (
    \`id\` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    \`user_key\` VARCHAR(191) NOT NULL,
    \`install_id\` VARCHAR(191) NULL,
    \`user_name\` VARCHAR(191) NULL,
    \`machine_id\` VARCHAR(191) NULL,
    \`machine_name\` VARCHAR(191) NULL,
    \`os_name\` VARCHAR(64) NULL,
    \`os_version\` VARCHAR(64) NULL,
    \`client_name\` VARCHAR(64) NULL,
    \`client_version\` VARCHAR(64) NULL,
    \`requirements_root_path\` VARCHAR(1024) NULL,
    \`wiki_root_path\` VARCHAR(1024) NULL,
    \`settings_json\` JSON NULL,
    \`settings_reported_at\` DATETIME(3) NULL,
    \`first_seen_at\` DATETIME(3) NULL,
    \`last_seen_at\` DATETIME(3) NULL,
    \`gmt_create\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    \`gmt_modified\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (\`id\`),
    UNIQUE KEY \`uk_sdd_users_user_key\` (\`user_key\`),
    KEY \`idx_sdd_users_install_id\` (\`install_id\`),
    KEY \`idx_sdd_users_machine_id\` (\`machine_id\`),
    KEY \`idx_sdd_users_first_seen_at\` (\`first_seen_at\`),
    KEY \`idx_sdd_users_last_seen_at\` (\`last_seen_at\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS \`sdd_skill_semantics\` (
    \`id\` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    \`semantic_code\` VARCHAR(64) NOT NULL,
    \`display_name\` VARCHAR(191) NOT NULL,
    \`description\` VARCHAR(1000) NULL,
    \`gmt_create\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    \`gmt_modified\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (\`id\`),
    UNIQUE KEY \`uk_sdd_skill_semantics_code\` (\`semantic_code\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS \`sdd_skill_aliases\` (
    \`id\` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    \`semantic_id\` BIGINT UNSIGNED NOT NULL,
    \`skill_name\` VARCHAR(191) NOT NULL,
    \`gmt_create\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    \`gmt_modified\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (\`id\`),
    UNIQUE KEY \`uk_sdd_skill_aliases_skill_name\` (\`skill_name\`),
    KEY \`idx_sdd_skill_aliases_semantic_id\` (\`semantic_id\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS \`otel_ingest_batches\` (
    \`id\` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    \`payload_hash\` CHAR(64) NOT NULL,
    \`user_id\` BIGINT UNSIGNED NULL,
    \`status\` VARCHAR(32) NOT NULL,
    \`status_reason\` VARCHAR(500) NULL,
    \`payload_bytes\` INT UNSIGNED NOT NULL,
    \`raw_log_count\` INT UNSIGNED NOT NULL DEFAULT 0,
    \`event_count\` INT UNSIGNED NOT NULL DEFAULT 0,
    \`derived_count\` INT UNSIGNED NOT NULL DEFAULT 0,
    \`duplicate_count\` INT UNSIGNED NOT NULL DEFAULT 0,
    \`last_duplicate_at\` DATETIME(3) NULL,
    \`received_at\` DATETIME(3) NOT NULL,
    \`parse_started_at\` DATETIME(3) NULL,
    \`parse_completed_at\` DATETIME(3) NULL,
    \`parse_duration_ms\` INT UNSIGNED NULL,
    \`retry_count\` INT UNSIGNED NOT NULL DEFAULT 0,
    \`last_error\` LONGTEXT NULL,
    \`gmt_create\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    \`gmt_modified\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (\`id\`),
    UNIQUE KEY \`uk_otel_ingest_batches_payload_hash\` (\`payload_hash\`),
    KEY \`idx_otel_ingest_batches_status_received\` (\`status\`, \`received_at\`),
    KEY \`idx_otel_ingest_batches_user_received\` (\`user_id\`, \`received_at\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS \`otel_raw_payloads\` (
    \`id\` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    \`batch_id\` BIGINT UNSIGNED NOT NULL,
    \`payload_json\` LONGTEXT NOT NULL,
    \`payload_bytes\` INT UNSIGNED NOT NULL,
    \`content_type\` VARCHAR(128) NULL,
    \`expires_at\` DATETIME(3) NOT NULL,
    \`gmt_create\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    \`gmt_modified\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (\`id\`),
    UNIQUE KEY \`uk_otel_raw_payloads_batch_id\` (\`batch_id\`),
    KEY \`idx_otel_raw_payloads_expires_at\` (\`expires_at\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS \`ingest_outbox\` (
    \`id\` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    \`event_type\` VARCHAR(64) NOT NULL,
    \`aggregate_id\` BIGINT UNSIGNED NOT NULL,
    \`payload_json\` JSON NULL,
    \`status\` VARCHAR(32) NOT NULL,
    \`attempts\` INT UNSIGNED NOT NULL DEFAULT 0,
    \`max_attempts\` INT UNSIGNED NOT NULL DEFAULT 20,
    \`next_retry_at\` DATETIME(3) NULL,
    \`locked_by\` VARCHAR(191) NULL,
    \`locked_until\` DATETIME(3) NULL,
    \`last_error\` LONGTEXT NULL,
    \`dispatched_at\` DATETIME(3) NULL,
    \`gmt_create\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    \`gmt_modified\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (\`id\`),
    UNIQUE KEY \`uk_ingest_outbox_event_aggregate\` (\`event_type\`, \`aggregate_id\`),
    KEY \`idx_ingest_outbox_status_retry\` (\`status\`, \`next_retry_at\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS \`otel_log_events\` (
    \`id\` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    \`event_id\` CHAR(64) NOT NULL,
    \`batch_id\` BIGINT UNSIGNED NOT NULL,
    \`user_id\` BIGINT UNSIGNED NULL,
    \`session_id\` VARCHAR(191) NULL,
    \`prompt_id\` VARCHAR(191) NULL,
    \`trace_id\` VARCHAR(64) NULL,
    \`span_id\` VARCHAR(64) NULL,
    \`event_name\` VARCHAR(191) NOT NULL,
    \`display_name\` VARCHAR(191) NULL,
    \`service_name\` VARCHAR(191) NULL,
    \`service_version\` VARCHAR(64) NULL,
    \`severity_text\` VARCHAR(64) NULL,
    \`severity_number\` INT NULL,
    \`event_time\` DATETIME(3) NULL,
    \`observed_at\` DATETIME(3) NULL,
    \`attributes_json\` JSON NULL,
    \`resource_json\` JSON NULL,
    \`body_json\` JSON NULL,
    \`body_text\` LONGTEXT NULL,
    \`expires_at\` DATETIME(3) NOT NULL,
    \`gmt_create\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    \`gmt_modified\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (\`id\`),
    UNIQUE KEY \`uk_otel_log_events_event_id\` (\`event_id\`),
    KEY \`idx_otel_log_events_batch_id\` (\`batch_id\`),
    KEY \`idx_otel_log_events_user_id\` (\`user_id\`),
    KEY \`idx_otel_log_events_session_id\` (\`session_id\`),
    KEY \`idx_otel_log_events_prompt_id\` (\`prompt_id\`),
    KEY \`idx_otel_log_events_event_name\` (\`event_name\`),
    KEY \`idx_otel_log_events_service_version\` (\`service_version\`),
    KEY \`idx_otel_log_events_event_time\` (\`event_time\`),
    KEY \`idx_otel_log_events_expires_at\` (\`expires_at\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS \`sdd_interactions\` (
    \`id\` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    \`interaction_key\` CHAR(64) NOT NULL,
    \`user_id\` BIGINT UNSIGNED NULL,
    \`session_id\` VARCHAR(191) NULL,
    \`prompt_id\` VARCHAR(191) NULL,
    \`request_event_id\` CHAR(64) NULL,
    \`response_event_id\` CHAR(64) NULL,
    \`status\` VARCHAR(32) NOT NULL,
    \`model\` VARCHAR(128) NULL,
    \`command_name\` VARCHAR(191) NULL,
    \`command_source\` VARCHAR(191) NULL,
    \`pairing_method\` VARCHAR(64) NOT NULL,
    \`started_at\` DATETIME(3) NULL,
    \`completed_at\` DATETIME(3) NULL,
    \`duration_ms\` INT UNSIGNED NULL,
    \`source_batch_id\` BIGINT UNSIGNED NULL,
    \`evidence_json\` JSON NULL,
    \`gmt_create\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    \`gmt_modified\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (\`id\`),
    UNIQUE KEY \`uk_sdd_interactions_interaction_key\` (\`interaction_key\`),
    KEY \`idx_sdd_interactions_user_id\` (\`user_id\`),
    KEY \`idx_sdd_interactions_session_id\` (\`session_id\`),
    KEY \`idx_sdd_interactions_prompt_id\` (\`prompt_id\`),
    KEY \`idx_sdd_interactions_started_at\` (\`started_at\`),
    KEY \`idx_sdd_interactions_source_batch_id\` (\`source_batch_id\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS \`sdd_interaction_texts\` (
    \`id\` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    \`interaction_id\` BIGINT UNSIGNED NOT NULL,
    \`prompt_text\` LONGTEXT NULL,
    \`response_text\` LONGTEXT NULL,
    \`response_json\` LONGTEXT NULL,
    \`expires_at\` DATETIME(3) NOT NULL,
    \`gmt_create\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    \`gmt_modified\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (\`id\`),
    UNIQUE KEY \`uk_sdd_interaction_texts_interaction_id\` (\`interaction_id\`),
    KEY \`idx_sdd_interaction_texts_expires_at\` (\`expires_at\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS \`sdd_skill_usages\` (
    \`id\` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    \`usage_key\` CHAR(64) NOT NULL,
    \`semantic_id\` BIGINT UNSIGNED NULL,
    \`alias_id\` BIGINT UNSIGNED NULL,
    \`interaction_id\` BIGINT UNSIGNED NULL,
    \`work_item_id\` BIGINT UNSIGNED NULL,
    \`user_id\` BIGINT UNSIGNED NULL,
    \`session_id\` VARCHAR(191) NULL,
    \`prompt_id\` VARCHAR(191) NULL,
    \`raw_skill_name\` VARCHAR(191) NOT NULL,
    \`skill_source\` VARCHAR(191) NULL,
    \`invocation_trigger\` VARCHAR(191) NULL,
    \`command_name\` VARCHAR(191) NULL,
    \`service_version\` VARCHAR(64) NULL,
    \`observed_version\` VARCHAR(64) NULL,
    \`matched_by\` VARCHAR(64) NOT NULL,
    \`rule_version\` VARCHAR(32) NOT NULL,
    \`event_sequence\` INT UNSIGNED NULL,
    \`status\` VARCHAR(32) NOT NULL,
    \`event_time\` DATETIME(3) NULL,
    \`gmt_create\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    \`gmt_modified\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (\`id\`),
    UNIQUE KEY \`uk_sdd_skill_usages_usage_key\` (\`usage_key\`),
    KEY \`idx_sdd_skill_usages_semantic_id\` (\`semantic_id\`),
    KEY \`idx_sdd_skill_usages_interaction_id\` (\`interaction_id\`),
    KEY \`idx_sdd_skill_usages_work_item_id\` (\`work_item_id\`),
    KEY \`idx_sdd_skill_usages_user_id\` (\`user_id\`),
    KEY \`idx_sdd_skill_usages_session_id\` (\`session_id\`),
    KEY \`idx_sdd_skill_usages_prompt_id\` (\`prompt_id\`),
    KEY \`idx_sdd_skill_usages_raw_skill_name\` (\`raw_skill_name\`),
    KEY \`idx_sdd_skill_usages_service_version\` (\`service_version\`),
    KEY \`idx_sdd_skill_usages_observed_version\` (\`observed_version\`),
    KEY \`idx_sdd_skill_usages_event_time\` (\`event_time\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS \`sdd_work_items\` (
    \`id\` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    \`work_item_key\` CHAR(64) NOT NULL,
    \`requirements_repo_name\` VARCHAR(191) NULL,
    \`business_domain\` VARCHAR(191) NULL,
    \`work_item_slug\` VARCHAR(191) NOT NULL,
    \`work_item_title\` VARCHAR(500) NULL,
    \`relative_dir\` VARCHAR(1024) NOT NULL,
    \`first_seen_at\` DATETIME(3) NULL,
    \`last_seen_at\` DATETIME(3) NULL,
    \`gmt_create\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    \`gmt_modified\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (\`id\`),
    UNIQUE KEY \`uk_sdd_work_items_work_item_key\` (\`work_item_key\`),
    KEY \`idx_sdd_work_items_business_domain\` (\`business_domain\`),
    KEY \`idx_sdd_work_items_work_item_slug\` (\`work_item_slug\`),
    KEY \`idx_sdd_work_items_last_seen_at\` (\`last_seen_at\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS \`sdd_work_item_artifacts\` (
    \`id\` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    \`artifact_key\` CHAR(64) NOT NULL,
    \`work_item_id\` BIGINT UNSIGNED NOT NULL,
    \`artifact_type\` VARCHAR(64) NOT NULL,
    \`artifact_relative_path\` VARCHAR(1024) NOT NULL,
    \`artifact_full_path\` VARCHAR(2048) NOT NULL,
    \`system_module\` VARCHAR(191) NULL,
    \`first_seen_event_id\` CHAR(64) NULL,
    \`first_seen_at\` DATETIME(3) NULL,
    \`last_seen_at\` DATETIME(3) NULL,
    \`gmt_create\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    \`gmt_modified\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (\`id\`),
    UNIQUE KEY \`uk_sdd_work_item_artifacts_artifact_key\` (\`artifact_key\`),
    KEY \`idx_sdd_work_item_artifacts_work_item_id\` (\`work_item_id\`),
    KEY \`idx_sdd_work_item_artifacts_artifact_type\` (\`artifact_type\`),
    KEY \`idx_sdd_work_item_artifacts_system_module\` (\`system_module\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS \`sdd_errors\` (
    \`id\` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    \`error_key\` CHAR(64) NOT NULL,
    \`user_id\` BIGINT UNSIGNED NULL,
    \`batch_id\` BIGINT UNSIGNED NULL,
    \`event_id\` CHAR(64) NULL,
    \`interaction_id\` BIGINT UNSIGNED NULL,
    \`usage_id\` BIGINT UNSIGNED NULL,
    \`work_item_id\` BIGINT UNSIGNED NULL,
    \`error_type\` VARCHAR(128) NOT NULL,
    \`severity\` VARCHAR(32) NOT NULL,
    \`source\` VARCHAR(128) NULL,
    \`retryable\` TINYINT(1) NOT NULL DEFAULT 0,
    \`error_message_hash\` CHAR(64) NULL,
    \`error_message\` LONGTEXT NULL,
    \`stack_hash\` CHAR(64) NULL,
    \`stack_trace\` LONGTEXT NULL,
    \`event_time\` DATETIME(3) NULL,
    \`gmt_create\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    \`gmt_modified\` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (\`id\`),
    UNIQUE KEY \`uk_sdd_errors_error_key\` (\`error_key\`),
    KEY \`idx_sdd_errors_user_id\` (\`user_id\`),
    KEY \`idx_sdd_errors_batch_id\` (\`batch_id\`),
    KEY \`idx_sdd_errors_event_id\` (\`event_id\`),
    KEY \`idx_sdd_errors_interaction_id\` (\`interaction_id\`),
    KEY \`idx_sdd_errors_usage_id\` (\`usage_id\`),
    KEY \`idx_sdd_errors_work_item_id\` (\`work_item_id\`),
    KEY \`idx_sdd_errors_error_type\` (\`error_type\`),
    KEY \`idx_sdd_errors_severity\` (\`severity\`),
    KEY \`idx_sdd_errors_error_message_hash\` (\`error_message_hash\`),
    KEY \`idx_sdd_errors_event_time\` (\`event_time\`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
];

const dropOrder = [
  'sdd_errors',
  'sdd_work_item_artifacts',
  'sdd_work_items',
  'sdd_skill_usages',
  'sdd_interaction_texts',
  'sdd_interactions',
  'otel_log_events',
  'ingest_outbox',
  'otel_raw_payloads',
  'otel_ingest_batches',
  'sdd_skill_aliases',
  'sdd_skill_semantics',
  'sdd_users',
];
